--创建数据库--
CREATE DATABASE HOME_WORK01;

---创建用户表
CREATE TABLE USER_INFO
(
   ID             INT  AUTO_INCREMENT,
   USER_NAME      VARCHAR(100)   NOT NULL,
   USER_BIRTHDAY  VARCHAR(10),
   USER_GENDER    CHAR(1),
   USER_AGE       INT,
   USER_ADDRESS   VARCHAR(200),
   CREATE_TIME    TIMESTAMP NOT NULL DEFAULT NOW(),
   MODIFY_TIME    TIMESTAMP NOT NULL DEFAULT NOW(),
   PRIMARY KEY(ID)
);


---创建商品表

CREATE TABLE GOODS_INFO
(
   ID          INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
   CATEGORY_ID CHAR(3) NOT NULL,
   NAME        VARCHAR(120) NOT NULL,
   PRICE       DECIMAL(10,2) NOT NULL,
   STOCK       INT UNSIGNED NOT NULL DEFAULT 0,
   IS_DELETE   TINYINT UNSIGNED NOT NULL DEFAULT 0,
   CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   UPDATE_TIME DATETIME DEFAULT NULL
);

---创建订单表

CREATE TABLE ORDER_INFO 
(
  ID              INT NOT NULL AUTO_INCREMENT,
  ORDER_NO        VARCHAR(50) NOT NULL,
  ORDER_SEQUENCE  VARCHAR(32) NOT NULL,
  ORDER_STATUS    CHAR(3) NOT NULL,
  ORDER_AMOUNT    DECIMAL(20,2) NOT NULL,
  CREATED_BY      VARCHAR(100),
  CREATED_DATE    DATETIME NOT NULL DEFAULT NOW(),
  UPDATED_BY      VARCHAR(100),
  UPDATED_DATE    DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (ID)
)；