server:
  port: 8080
spring:
  datasource:
    master: # 主机
      jdbc-url: jdbc:mysql://localhost:3306/HOME_WORK01?characterEncoding=utf-8&useSSL=false
      username: root
      password: root
    slave: # 从机
      jdbc-url: jdbc:mysql://localhost:3316/HOME_WORK01?characterEncoding=utf-8&useSSL=false
      username: root
      password: root
